---
title: "Michael D. Garber"
---

As a social and environmental epidemiologist, I study how places can be designed and managed to support population health and climate resilience. I have led research

-   investigating how bicycling infrastructure affects [bicycling](https://pmc.ncbi.nlm.nih.gov/articles/PMC9211442/) and bicycling [safety](https://pmc.ncbi.nlm.nih.gov/articles/PMC10773466/),

-   estimating health impacts of urban green space [locally](https://www.sciencedirect.com/science/article/pii/S0160412023003239) and [globally](https://www.nature.com/articles/s43247-024-01803-y), and

-   describing how [parking](https://link.springer.com/article/10.1007/s40572-024-00465-4) policy may affect population health and equity.

    <br>

I have methodological expertise in

-   policy evaluation and quasi-experimental methods,

-   health-impact assessment,

-   the validity of active-mobility data generated by smartphones,

-   the design of case-control studies, and

-   spatial data science using R.

    <br>

I earned my MPH and PhD in Epidemiology from Emory University Rollins School of Public Health, and I am currently a post-doctoral researcher with UC San Diego. I have authored 25 peer-reviewed journal articles, including 13 as lead author. In 2022, I received the [Rothman Epidemiology Prize](https://journals.lww.com/epidem/fulltext/2022/07000/michael_d__garber,_winner_of_the_2022_rothman.1.aspx) for our [article](https://journals.lww.com/epidem/fulltext/2021/01000/at_risk_measure_sampling_in_case_control_studies.14.aspx) published in *Epidemiology*.

<br>

## **Recent publications**

[Parking and Public Health](https://link.springer.com/article/10.1007/s40572-024-00465-4)<br> Michael Garber, Tarik Benmarhnia, Jacob Mason, Emily Morales-Zamora, David Rojas-Rueda.<br>***Current Environmental Health Reports***. 2025<br>

[The epidemiologic case for urban health: conceptualizing and measuring the magnitude of challenges and potential benefits](https://f1000research.com/articles/13-950)<br> Michael Garber, Tarik Benmarhnia, Audrey de Nazelle, Mark Nieuwenhuijsen, David Rojas-Rueda.<br>***F1000 Research***. 2024<br>

<br>

## **Contact and profiles**

email: mdgarber\@ucsd.edu

Google Scholar [profile](https://scholar.google.com/citations?hl=en&user=r-MsgFsAAAAJ&view_op=list_works&sortby=pubdate)

ResearchGate: <https://www.researchgate.net/profile/Michael-Garber>

ORCID: [orcid.org/0000-0003-0122-5634](https://orcid.org/0000-0003-0122-5634)

GitHub: <https://github.com/michaeldgarber>

Linkedin: <https://www.linkedin.com/in/michaeldgarber/>
