---
title: "Papers"
---

<br> This page summarizes a selection of my published research by topic. A complete list of my publications can be found at my [Google Scholar profile](https://scholar.google.com/citations?hl=en&user=r-MsgFsAAAAJ&view_op=list_works&sortby=pubdate). I've linked to an open-access full text if available. I would happily send a full text of any pay-walled articles by email ([hi\@michaeldgarber.com](mailto:hi@michaeldgarber.com){.email}). <br> <br>

#### Effect of the built environment on bicycling and bicycling safety

My colleagues and I used the generalized synthetic control method to estimate effects of large-scale bicycle infrastructure projects in Atlanta, including the Atlanta BeltLine, on bicycling. We also conducted a case-control study to estimate the incidence rate of bicyclist crashes with cars per distance ridden on several types of bike infrastructure.

-   [Have paved trails and protected bike lanes led to more bicycling in Atlanta? A generalized synthetic-control analysis](https://journals.lww.com/epidem/Abstract/9900/Have_paved_trails_and_protected_bike_lanes_led_to.15.aspx)<br>Michael Garber, Dana Flanders, Kari Watkins, Felipe Lobelo, Michael Kramer, Lauren McCullough<br> ***Epidemiology***. 2022. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9211442/)) ([video abstract](https://www.youtube.com/watch?v=GJ7QzcFeCnk))<br> <br>
-   [Bicycle infrastructure and the incidence rate of crashes with cars: A case-control study with Strava data in Atlanta](https://www.sciencedirect.com/science/article/pii/S2214140523001056)<br>Michael Garber, Kari Watkins, Dana Flanders, Michael Kramer, Felipe Lobelo, Steve Mooney, David Ederer, Lauren McCullough<br> ***Journal of Transport & Health***. 2023. ([full-text](https://authors.elsevier.com/a/1hZkV7tR-3MpJW))<br> <br>

#### Sampling, selection bias, and mobile-device data

We have also aimed to better understand how epidemiologic concepts, including case-control sampling and conditions for no selection bias, can inform the valid use of data generated from mobile devices in research. I am most of proud of [this paper](https://journals.lww.com/epidem/Fulltext/2021/01000/At_risk_measure_Sampling_in_Case_Control_Studies.14.aspx), in which we extend case-control sampling principles to show how aggregated smartphone-generated data can be used to estimate the incidence rate ratio in epidemiologic studies.

-   [On selection bias in comparison measures of smartphone-generated population mobility: an illustration of no-bias conditions with a commercial data source](https://www.sciencedirect.com/science/article/abs/pii/S1047279722000370)<br>Michael Garber, Katie Labgold, Michael Kramer<br> ***Annals of Epidemiology***. 2022. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9202634/))

-   [At-risk-measure sampling in case-control studies with aggregated data](https://journals.lww.com/epidem/Fulltext/2021/01000/At_risk_measure_Sampling_in_Case_Control_Studies.14.aspx)<br> Michael Garber, Lauren McCullough, Steve Mooney, Michael Kramer, Kari Watkins, Felipe Lobelo, Dana Flanders<br> ***Epidemiology***. 2021. (full text above and in [PubMed Central](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7707160/)) ([GitHub repo](https://github.com/michaeldgarber/at-risk-measure-sampling)) (Winner of 2022 [Rothman Prize](https://journals.lww.com/epidem/Fulltext/2022/07000/Michael_D__Garber,_Winner_of_the_2022_Rothman.1.aspx))

-   [Comparing bicyclists who use smartphone apps to record rides with those who do not: Implications for representativeness and selection bias](https://www.sciencedirect.com/science/article/pii/S2214140518305590)<br>Michael Garber, Kari Watkins, Michael Kramer<br> ***Journal of Transport & Health***. 2019. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6959852/))

-   [Sampling and Sampling Frames in Big Data Epidemiology](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6662929/)<br> Steve Mooney, Michael Garber<br> ***Current Epidemiology Reports***. 2019. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6662929/)) <br> <br>

#### Causal-inference concepts

At Emory, I was a teaching assistant in a course covering methods for causal inference in observational data. Informed by this experience, I have written about how the potential-outcome model from epidemiology can be a useful frame for electoral questions and have commented on the utility of causal-inference tools for environmental epidemiology:

-   [A definition of the causal effect of a political party's nominee on the U.S. general presidential election using counterfactual response types](https://www.sciencedirect.com/science/article/pii/S1047279720301733?via%3Dihub)<br> Michael Garber, Lindsay Collin, Dana Flanders <br> ***Annals of Epidemiology***. 2020. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7412752/))

-   [Is the Smog Lifting? Causal Inference in Environmental Epidemiology](https://journals.lww.com/epidem/Fulltext/2019/05000/Is_the_Smog_Lifting___Causal_Inference_in.2.aspx)<br> Dana Flanders, Michael Garber<br> ***Epidemiology***. 2019. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6456370/))

-   [The Authors Respond](https://journals.lww.com/epidem/Fulltext/2019/11000/The_Authors_Respond.26.aspx)<br>Dana Flanders, Michael Garber<br> ***Epidemiology***. 2019. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6936609/)) <br> <br>

#### Physical fitness in children

Finally, I have conducted research on physical fitness in youth and its social and geographical determinants:

-   [Effect of Cardiorespiratory Fitness on Academic Achievement is Stronger in High-SES Elementary Schools Compared to Low](https://onlinelibrary.wiley.com/doi/10.1111/josh.12678)<br> Michael Garber, Kait Stanhope, Monica Shah, Patricia Cheung, Julie Gazmararian<br> ***Journal of School Health***. 2018.

-   [Geographical Variation in Health-Related Physical Fitness and Body Composition among Chilean 8th Graders: A Nationally Representative Cross-Sectional Study](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0108053)<br> Michael Garber, Marcelo Sajuria, Felipe Lobelo<br> ***PLOS ONE***. 2014. ([full text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4177890/)) <br> <br>
